# Generated by Django 4.2.1 on 2023-06-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('stock_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='quantity',
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='stock_transfer.stocktransfer')),
            ],
        ),
    ]
