# Generated by Django 4.2.1 on 2023-06-08 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_transfer', '0004_alter_stocktransfer_transfered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfered_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
