# Generated by Django 4.2.1 on 2023-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0005_alter_stocktransfer_transfered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
