# Generated by Django 4.2.1 on 2023-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0006_stocktransfer_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='is_processed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
