# Generated by Django 4.2.1 on 2023-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0007_alter_stocktransfer_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
