# Generated by Django 4.2.1 on 2023-06-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_customer'),
        ('stock_transfer', '0009_alter_transferitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='transfered_by',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='inventory.store'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='inventory.store'),
        ),
    ]
