# Generated by Django 4.2.1 on 2023-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0010_remove_stocktransfer_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('cartons', 'Cartons')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
