# Generated by Django 4.2.1 on 2023-06-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0012_alter_stocktransfer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='user',
            new_name='transfered_by',
        ),
    ]
