# Generated by Django 4.2.1 on 2023-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0013_rename_user_stocktransfer_transfered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
