# Generated by Django 4.2.1 on 2023-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0014_stocktransfer_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='transfered_by',
            new_name='transferred_by',
        ),
        migrations.AddField(
            model_name='transferitem',
            name='is_completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='is_completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
