# Generated by Django 4.2.1 on 2023-06-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0015_rename_transfered_by_stocktransfer_transferred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='is_completed',
        ),
    ]
