# Generated by Django 4.2.1 on 2023-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('cartons', 'Cartons')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
