# Generated by Django 3.2 on 2023-08-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
