# Generated by Django 3.2 on 2023-08-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_paymentmethod_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='code',
        ),
    ]
