# Generated by Django 3.2 on 2023-08-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_paymentmethod_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
