# Generated by Django 4.2.1 on 2023-06-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
