# Generated by Django 4.2.1 on 2023-06-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_sold_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='tendered_amount',
            new_name='rendered_amount',
        ),
    ]
