# Generated by Django 4.2.1 on 2023-06-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_tendered_amount_sale_rendered_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount_change',
            new_name='balance',
        ),
    ]
