# Generated by Django 4.2.1 on 2023-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_amount_change_sale_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('cartons', 'Cartons')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
