# Generated by Django 3.2 on 2023-08-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_paymentmethod_code'),
        ('sales', '0007_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.paymentmethod'),
        ),
    ]
